Añadidas clases para añadir propiedades adicionales a los pedidos
NeoRazorX/presupuestos_y_pedidos pull request #27
Opened 2017-08-17 09:10 UTC by shawe

Repartido en 5 modelos:
- Cabecera/pie del pedido
- Observaciones del pedido
- Líneas del pedido
- Observaciones de las líneas del pedido
- Desglose sobre las líneas del pedido

2017-08-17 09:47 UTC, NeoRazorX commented
Demasiadas clases con ninguna diferencia. Lo de cabecera, pie u observaciones lo puedes solucionar con una simple columna más, en lugar de una clase.

Y ya que estás, mejora el save() para que en el inserte guarde el id generado.

2017-08-21 22:16 UTC, shawe commented
Lo siento, no me acordaba de ese otro Pull-Request.

Sobre lo de que mencionas que son demasiadas clases lo sé, pero son las de info adicional que usa EDICOM para comunicar y debo almacenarla aunque por ahora no la use porqué FS no tenga soporte para algunas cosas. Si crees que no pega en presupuestos_y_pedidos, lo dejo en el propio plugin que eso no es problema, lo quería usar así tal cual porque ellos suministran esa info como archivos, y así lo leo y lo guardo como key-value asociado al documento sin perder info. Otra opción sería usar 1 columna adicional para indicarle el tipo de archivo de donde procede esa info, y con 1 única clase por tipo de documento pasaría, y creo que será como lo haré para simplificarlo un poco.

2017-08-21 22:19 UTC, NeoRazorX requested changes

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_linea_propiedad.php
> +class pedidocli_linea_propiedad extends \fs_model
En todo caso será linea_pedido_cliente_propiedad o linea_pedido_cliente_prop.

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_linea_propiedad.php
> +        parent::__construct('pedidocli_linea_propiedades');
lineaspedidoscli_prop

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_linea_propiedad.php
> +            $this->idpedido = $a['idpedido'];
$this->idpedido = intval($a['idpedido']);
Lo mismo con la siguiente.

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_linea_propiedad.php
> +        if (is_null($this->name) OR is_null($this->idpedido)) {
Si añades un id para la tabla y pones name, idpedido e idlinea como unique, simplificas mucho.
No tienes por qué repetir los errores de diseño de otras tablas.

2017-08-21 22:19 UTC, NeoRazorX commented on controller/ventas_pedido.php
> +                                $due_linea = $this->calcDUE(array($lineas[$k]->dtopor,$lineas[$k]->dtopor2,$lineas[$k]->dtopor3,$lineas[$k]->dtopor4));
Diría que falta la función calcDUE(). Además, esto no es FacturaScripts 2018, aquí las funciones se llaman_asi().
Si además mueves esa función a functions.php, podrás llamarla desde cualquier sitio sin necesidad de implementarla en cada clase.

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_loc_linea_propiedad.php
> +class pedidocli_loc_linea_propiedad extends \fs_model
Aquí la cosa empieza a complicarse innecesariamente. Mucha clase y demasiado parecidas.

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_propiedad.php
> +class pedidocli_propiedad extends \fs_model
pedido_cliente_propiedad o pedido_cliente_prop

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_propiedad.php
> +            $this->idpedido = $a['idpedido'];
$this->idpedido = intval($a['idpedido']);

2017-08-21 22:19 UTC, NeoRazorX commented on model/pedidocli_propiedad.php
> +        if (is_null($this->name) OR is_null($this->idpedido)) {
Añade id, unique(name,idpedido) y simplifica.

2017-08-21 22:19 UTC, NeoRazorX commented on view/ventas_pedido.html
> +      show = false;
El código para ocultar estas columnas se puede mover a nueva_venta.js

2017-08-22 07:41 UTC, shawe commented on model/pedidocli_linea_propiedad.php
> +        parent::__construct('pedidocli_linea_propiedades');
Lo he unificado en 1 sólo modelo, pedido_cliente_propiedad y pedido_proveedor_propiedad, tal y como comentas en el primer comentario.

2017-08-22 07:41 UTC, shawe commented on model/pedidocli_linea_propiedad.php
> +            $this->idpedido = $a['idpedido'];
Añadido

2017-08-22 07:42 UTC, shawe commented on controller/ventas_pedido.php
> +                                $due_linea = $this->calcDUE(array($lineas[$k]->dtopor,$lineas[$k]->dtopor2,$lineas[$k]->dtopor3,$lineas[$k]->dtopor4));
calcDUE y calcDescDUE los puse en fbase_controller, que es del que extienden ventas_presupuesto, ventas_pedido, ventas_albaran, ventas_factura.

Lo muevo a functions.php igualmente?

2017-08-22 07:43 UTC, shawe commented on model/pedidocli_propiedad.php
> +            $this->idpedido = $a['idpedido'];
Añadido

2017-08-22 07:47 UTC, shawe commented on model/pedidocli_linea_propiedad.php
> +class pedidocli_linea_propiedad extends \fs_model
Lo he unificado en 1 sólo modelo, pedido_cliente_propiedad y pedido_proveedor_propiedad, tal y como comentas en el primer comentario.
Me falta preparar para las líneas haciendo lo que explicas.

2017-08-22 07:47 UTC, shawe commented on model/pedidocli_linea_propiedad.php
> +        if (is_null($this->name) OR is_null($this->idpedido)) {
Pendiente

2017-08-22 07:48 UTC, shawe commented on model/pedidocli_loc_linea_propiedad.php
> +class pedidocli_loc_linea_propiedad extends \fs_model
Eliminada, la unificaré con una global para líneas.

2017-08-22 07:48 UTC, shawe commented on model/pedidocli_propiedad.php
> +class pedidocli_propiedad extends \fs_model
Lo he unificado en 1 sólo modelo, pedido_cliente_propiedad y pedido_proveedor_propiedad, tal y como comentas en el primer comentario.

2017-08-22 07:49 UTC, shawe commented on model/pedidocli_propiedad.php
> +        if (is_null($this->name) OR is_null($this->idpedido)) {
Pendiente como la anterior

2017-08-22 08:05 UTC, shawe commented on view/ventas_pedido.html
> +      show = false;
Hecho

2017-08-22 08:12 UTC, shawe commented on model/pedidocli_propiedad.php
> +        if (is_null($this->name) OR is_null($this->idpedido)) {
Hecho

2017-08-22 08:13 UTC, shawe commented on model/pedidocli_linea_propiedad.php
> +        if (is_null($this->name) OR is_null($this->idpedido)) {
Hecho

2017-08-22 08:46 UTC, shawe commented
He aplicado las correcciones e unificación que me has indicado y he movido esos modelos conflictivos al plugin en cuestión que por ahora va a ser el único usarlos.

He aplicado los cambios que me has dicho en todo lo demás y adicionalmente he añadido las correcciones indicadas por scrutinizer en todo lo que había hecho.

2017-09-06 16:31 UTC, NeoRazorX approved these changes

2017-09-07 21:41 UTC, merged